import { useState } from "react";
import { ChevronDown } from "lucide-react";
import PageHero from "../../components/landing/PageHero";

const FAQS = [
  { q: "Who is StudyHub for?", a: "Reading libraries, UPSC/SSC/NEET/JEE study spaces, and student co-working rooms — anywhere students pay to study, not borrow books." },
  { q: "Does StudyHub manage books?", a: "No. StudyHub is built entirely around seats, study time, fees, and student progress — not a book catalogue or lending system." },
  { q: "How do students mark attendance?", a: "Students punch in and out from their phone, or scan a desk QR code generated by the library admin." },
  { q: "Can one super admin manage multiple libraries?", a: "Yes — the Super Admin console is built for managing many libraries (tenants) from a single dashboard, each with its own admin and students." },
  { q: "Is my library's data visible to other libraries?", a: "No. Each library's students, seats, and fees are isolated to that library's admin account." },
  { q: "What if I run multiple branches?", a: "Each branch can be registered as its own library under the same owner, with a shared Super Admin view across both." },
];

export default function FAQPage() {
  const [open, setOpen] = useState(0);
  return (
    <>
      <PageHero eyebrow="FAQ" title="Frequently asked questions" />
      <section className="max-w-2xl mx-auto px-5 lg:px-8 pb-24 space-y-3">
        {FAQS.map((f, i) => (
          <div key={f.q} className="rounded-xl border border-ink-700 bg-ink-850 overflow-hidden">
            <button onClick={() => setOpen(open === i ? -1 : i)} className="w-full flex items-center justify-between px-5 py-4 text-left">
              <span className="text-sm font-medium text-ink-100">{f.q}</span>
              <ChevronDown size={16} className={`text-ink-400 transition-transform shrink-0 ml-3 ${open === i ? "rotate-180" : ""}`} />
            </button>
            {open === i && <div className="px-5 pb-4 text-sm text-ink-400 leading-relaxed">{f.a}</div>}
          </div>
        ))}
      </section>
    </>
  );
}
